### ISSUE TITLE
Replace wrong housing lyph in ard-arm-cardiac.json

### ISSUE THREAD

**Issue by albatros13** [open-physiology/apinatomy-models#24]
As discovered while checking https://github.com/open-physiology/open-physiology-viewer/issues/208, chains ac-vent-epi-term-6 and ac-atrial-epi-term-6 in aacar model https://github.com/open-physiology/apinatomy-models/blob/410289fb2666330cbc5cd4448c58a06922ec6525/models/ard-arm-cardiac/source/ard-arm-cardiac.json refer to non-existing lyph 74 which has to be replaced to A74 (the viewer issues the appropriate warning about this:
Failed to find chain level housing lyph
"74"
Failed to find chain level housing lyph
"74"
)

**Comment by tgbugs** [comment]
Just encounter this again today and fixed it.
